version: "3.4"
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - matheus-network
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - matheus-network
  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3308"
    env_file:
      - docker.env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    networks:
      - matheus-network
  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3310:3310"
    env_file:
      - docker.env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    networks:
      - matheus-network
  naming-server:
    image: mattv97/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - matheus-network
  api-gateway:
    image: mattv97/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - matheus-network
  cambio-service:
    image: mattv97/cambio-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.USERNAME: ${DB_USERNAME}
      SPRING.PASSWORD: ${DB_PASSWORD}
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: ${DB_USERNAME}
      SPRING.FLYWAY.PASSWORD: ${DB_PASSWORD}
    networks:
      - matheus-network
  book-service:
    image: mattv97/book-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    ports:
      - "8100:8100"
    env_file:
      - docker.env
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.USERNAME: ${DB_USERNAME}
      SPRING.PASSWORD: ${DB_PASSWORD}
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: ${DB_USERNAME}
      SPRING.FLYWAY.PASSWORD: ${DB_PASSWORD}
    networks:
      - matheus-network
networks:
  matheus-network:
    driver: bridge